#!/bin/sh /etc/rc.common

# Copyright (C) 2025 by sirpdboy <sirpdboy@qq.com>

START=99
USE_PROCD=1

PROG=/usr/sbin/change-mac
TMPMAC=/tmp/tmpchange-mac.tmp
NAME="change-mac"
SECTION=".basic."

changemac() {
enabled=$(uci -q get "${NAME}${SECTION}enabled" || echo 0)
interfaces=$(uci -q get "${NAME}${SECTION}interface" || echo eth0)
[ "x$enabled" == "x1" ] && $PROG  $interfaces > $TMPMAC

}

boot() {

	delaytime=$(uci -q get "${NAME}${SECTION}delaytime")
	sleep $delaytime
	start_service
}

start_service() {
	[ ! -s $TMPMAC ] && changemac
	pingarps
}

pingarps() {
    interfaces=$(uci -q get "${NAME}${SECTION}interface" || echo eth0)
    arp_drop=$(uci -q get "${NAME}${SECTION}arp_drop" || echo 0)
    ping_drop=$(uci -q get "${NAME}${SECTION}ping_drop" || echo 0)
for iface in $interfaces; do
    if [ "$arp_drop" -eq 1 ]; then
        echo "Disabling ARP on interface $iface"
        sed -i "/net.ipv4.conf.$iface.arp_ignore/d" /etc/sysctl.conf
        sed -i "/net.ipv4.conf.$iface.arp_announce/d" /etc/sysctl.conf
        echo "net.ipv4.conf.$iface.arp_ignore=1" >> /etc/sysctl.conf
        echo "net.ipv4.conf.$iface.arp_announce=2" >> /etc/sysctl.conf
        echo 1 > /proc/sys/net/ipv4/conf/$iface/arp_ignore
        echo 2 > /proc/sys/net/ipv4/conf/$iface/arp_announce
    else
        echo "Restoring default ARP on interface $iface"
        sed -i "/net.ipv4.conf.$iface.arp_ignore/d" /etc/sysctl.conf
        sed -i "/net.ipv4.conf.$iface.arp_announce/d" /etc/sysctl.conf
        echo 0 > /proc/sys/net/ipv4/conf/$iface/arp_ignore
        echo 0 > /proc/sys/net/ipv4/conf/$iface/arp_announce
    fi
done
    
    uci -q delete firewall.$(uci -q show firewall | grep "Block-wan-PING" | cut -d'.' -f2| head -1)
    uci -q delete firewall.$(uci -q show firewall | grep "Block-lan-PING" | cut -d'.' -f2| head -1)
    if [ "$ping_drop" -eq 1 ]; then
        echo "Blocking ICMP PING from WAN"
        uci -q add firewall rule  2>/dev/null
        uci -q set firewall.@rule[-1].name='Block-wan-PING'
        uci -q set firewall.@rule[-1].src='wan'
        uci -q set firewall.@rule[-1].proto='icmp'
        uci -q set firewall.@rule[-1].icmp_type='echo-request'
        uci -q set firewall.@rule[-1].target='REJECT'
	echo "Blocking ICMP PING from lan"
        uci -q add firewall rule  2>/dev/null
        uci -q set firewall.@rule[-1].name='Block-lan-PING'
        uci -q set firewall.@rule[-1].src='lan'
        uci -q set firewall.@rule[-1].proto='icmp'
        uci -q set firewall.@rule[-1].icmp_type='echo-request'
        uci -q set firewall.@rule[-1].target='REJECT'
    fi
    
    sysctl -p /etc/sysctl.conf 2>/dev/null
    uci commit firewall 2>/dev/null
    /etc/init.d/firewall restart 2>/dev/null
}

restore() {
	for _net in $(uci get ${NAME}${SECTION}network); do uci delete network.$_net.macaddr 2>/dev/null; done
	uci commit network 2>/dev/null
	/etc/init.d/network restart 2>/dev/null
}