#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021-2025  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/luci-app-lucky

# This file is part of lucky .
#
# This is free software, licensed under the Apache License, Version 2.0 .


START=99
USE_PROCD=1

CONF="lucky"
PROG=/usr/bin/lucky
configdir='/etc/lucky'



get_config() {
  config_get_bool enabled $1 enabled 0
  config_get_bool logger $1 logger 1
  config_get port $1 port 16601
  config_get SafeURL $1 safe 

}

init_config(){
	config_load "$CONF"
	config_foreach get_config "$CONF"
}


start_run() {
	enabled=$(uci -q get $CONF.$CONF.enabled ) || enabled="0"
	logger=$(uci -q get $CONF.$CONF.logger ) || logger="1"
	port=$(uci -q get $CONF.$CONF.port ) || port="16601"
	SafeURL=$(uci -q get $CONF.$CONF.safe ) || SafeURL=""
	[ "x$enabled" = "x1" ] || return 1
	[ ! -d $configdir ] && mkdir -p $configdir 2>/dev/null
	[ $port ] && $(which lucky) -setconf -key AdminWebListenPort -value $port -cd $configdir
	[ $SafeURL ] && $(which lucky) -setconf -key SafeURL -value $SafeURL -cd $configdir
	procd_open_instance
	procd_set_param command $PROG -cd "$configdir"
	[ "x$logger" == x1 ] && procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance

}

start_service() {
  start_run
}


service_triggers() {
	procd_add_reload_trigger lucky
}
