#!/bin/sh /etc/rc.common
# 2022 jjm2473

START=99

check_service() {
    local service_name="$1"
    if [ -f "/usr/lib/lua/luci/controller/$service_name" ]; then
        return 0
    else
        return 1
    fi
}
boot() {
	# tune printk level after success boot, avoid noise in console
	echo '4 5 1 7' > /proc/sys/kernel/printk
	check_service "dockerman.lua" || {
		/etc/init.d/dockerd disable
		/etc/init.d/dockerd stop
	}
	# notify console system is ready
	sleep 1
	local pids=`pgrep -P 1 askfirst 2>/dev/null`
	if [ -n "$pids" ]; then
		local pid
		for pid in $pids; do
			echo -ne "\033[1A\033[K""\033[1A\033[K"
			echo "EzOpWrt is ready!" >/proc/$pid/fd/1
			echo "Please press Enter to activate this console." >/proc/$pid/fd/1
		done
	fi
}
