#!/bin/sh
# Copyright (C) 2022 jjm2473

uci -q batch <<-EOF >/dev/null
    set system.@system[-1].zonename='Asia/Shanghai'
    set system.@system[-1].timezone='CST-8'
    commit system
EOF

# uci set dockerd.globals.data_root=/opt/docker


uci -q batch <<-EOF >/dev/null
    commit dockerd
EOF

uci -q batch <<-EOF >/dev/null
    set luci.apply.rollback=30
    set luci.apply.holdoff=2
    commit luci
EOF

# uci set luci.main.sessiontime='2592000'
# uci set luci.main.sessionkeep='1'
# uci set luci.main.reqtimeout='300'

# uci set uhttpd.main.session_timeout='2592000'
# uci set uhttpd.main.session_keepalive='1'
# uci set uhttpd.main.cookie_lifetime='2592000'
# uci set uhttpd.main.max_requests='100'

# uci commit luci
# uci commit uhttpd

/etc/init.d/uhttpd restart
exit 0
