#!/bin/sh
# Copyright (C) 2022 jjm2473

uci -q batch <<-EOF >/dev/null
    set system.@system[-1].zonename='Asia/Shanghai'
    set system.@system[-1].timezone='CST-8'
    commit system
EOF

# uci set dockerd.globals.data_root=/opt/docker


uci -q batch <<-EOF >/dev/null
    commit dockerd
EOF

uci -q batch <<-EOF >/dev/null
    set luci.apply.rollback=30
    set luci.apply.holdoff=2
    commit luci
EOF

# samba4 share
sed -i 's/invalid users = root/# invalid users = root/g' /etc/samba/smb.conf.template

# uci set uhttpd.main.max_requests=50
# uci set uhttpd.main.max_connections=20
# uci set uhttpd.main.script_timeout=30
# uci set uhttpd.main.network_timeout=15
# uci set uhttpd.main.http_keepalive=10
uci set uhttpd.main.rfc1918_filter=0

uci commit luci
uci commit uhttpd
/etc/init.d/uhttpd restart

exit 0
