#!/bin/sh
chmod +x /etc/init.d/kucat
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@kucat[-1]
	add ucitrack kucat
	set ucitrack.@kucat[-1].init=kucat
	commit ucitrack
EOF
[ "x$(uci -q get kucat.@basic[0].mode)" = "x" ]  && /etc/config/kucat reset
rm -f /tmp/luci-indexcache

exit 0
