#!/bin/sh

# EzOpenWrt系统配置脚本
check_service() {
    local service_name="$1"
    [ -f "/usr/lib/lua/luci/controller/$service_name" ] && return 0 || return 1
}
ver=$(uci -q get base_config.@base[0].ver)
test -n "$ver" || {
    touch /etc/config/base_config
    uci -q add base_config base >/dev/null 2>&1
    ver=0
}

uci -q set luci.main.lang='auto'
[ -f '/www/luci-static/kucat/css/style.css' ] && uci -q set luci.main.mediaurlbase='/luci-static/kucat'

debug=0
uci -q set fstab.@global[0].check_fs=1

if [ -f '/etc/ezopenwrt_version' ]; then
    frmware=$(cat /etc/ezopenwrt_version | awk -F '_' '{printf $2}')
    if [ "$frmware" = "Super" ] || [ "$frmware" = "Mini" ] || [ "$frmware" = "dz" ]; then
        sed -i 's/nas/services/g' /usr/lib/lua/luci/controller/samba4.lua
        sed -i 's/nas/services/g' /usr/share/luci/menu.d/luci-app-samba4.json
        sed -i 's/vpn/services/g' /usr/share/luci/menu.d/luci-app-zerotier.json
    fi
fi

rm -rf /usr/share/luci/menu.d/luci-app-attendedsysupgrade.json
rm -rf /www/luci-static/resources/view/status/include/11*


test $ver -lt 1 && {
    ver=1
    uci -q del dhcp.lan.ignore
    uci -q del dhcp.lan.ra_slaac
    uci -q del network.lan.delegate
    uci -q set network.lan.proto='static'
    uci -q commit network
    [ "$debug" = "1" ] && echo "Version updated to: $ver"
}

test $ver -lt 2 && {
    for file in ddns.htm minidlna.htm mwan.htm upnp.htm; do
        [ -f "/usr/lib/lua/luci/view/admin_status/index/${file}" ] && rm -f "/usr/lib/lua/luci/view/admin_status/index/${file}"
    done
    
    ver=2
    uci -q set system.@system[0].hostname='EzOpWrt'
    uci -q commit system
    sed -i 's/root.*/root::0:0:99999:7:::/g' /etc/shadow
    [ "$debug" = "1" ] && echo "Version updated to: $ver"
}

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
    uci -q batch <<EOF
        set luci.main.lang="auto"
        commit luci
        set system.@imm_init[0].lang="1"
        commit system
EOF
fi

ln -sf "/sbin/ip" "/usr/bin/ip"

. /etc/os-release
case "$DISTRIB_TARGET" in
    "bcm4908"/*|"bcm53xx"/*|"ramips/mt7621"|"x86"/*)
        if ! uci -q get system.@imm_init[0].packet_steering > "/dev/null"; then
            uci -q batch <<EOF
                set network.globals="globals"
                set network.@globals[0].packet_steering="1"
                commit network
                set system.@imm_init[0].packet_steering="1"
                commit system
EOF
        fi
        ;;
esac

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
    uci -q batch <<EOF
        set system.@system[0].timezone="CST-8"
        set system.@system[0].zonename="Asia/Shanghai"
        delete system.ntp.server
        add_list system.ntp.server="ntp.tencent.com"
        add_list system.ntp.server="ntp1.aliyun.com"
        add_list system.ntp.server="ntp.ntsc.ac.cn"
        add_list system.ntp.server="cn.ntp.org.cn"
        set system.@imm_init[0].system_chn="1"
        commit system
EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
    opkg_mirror="https://mirrors.vsean.net/openwrt"
    uci -q batch <<EOF
        set system.@imm_init[0].opkg_mirror="$opkg_mirror"
        commit system
EOF
fi

sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf
sed -i '/check_signature/d' /etc/opkg.conf

if [ -f "/etc/ezopenwrt_version" ]; then
    . /etc/ezopenwrt_version
    [ -n "$EZVER" ] && {
        sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
        sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
        echo "DISTRIB_DESCRIPTION='${EZVER}'" >> /etc/openwrt_release
        echo "DISTRIB_REVISION='${EZVER}'" >> /etc/openwrt_release
        sed -i '/OPENWRT_RELEASE/d' /etc/os-release
        echo "OPENWRT_RELEASE='${EZVER}'" >> /etc/os-release
    }
fi

sed -i 's/immortalwrt/openwrt/g' /etc/config/luci

for option in syn_flood fullcone fullcone6 flow_offloading flow_offloading_hw synflood_protect; do
    uci -q del firewall.@defaults[0].$option
done

CURRENT_HASH=$(grep -o 'kmods/[^/]*' /etc/opkg/distfeeds.conf 2>/dev/null | cut -d/ -f2)
        kernelver=$(echo "$CURRENT_HASH" | sed 's/-.*//' | cut -d. -f1-3)
        NEW_HASH=""

        response=$(curl -fks --max-time 10 "https://mirror.nju.edu.cn/immortalwrt/releases/24.10-SNAPSHOT/targets/x86/64/kmods/" 2>/dev/null)
        if [ -n "$response" ]; then
            NEW_HASH=$(echo "$response" | grep "$kernelver" | awk -F 'href="' '{print $2}' | awk -F '/"' '{print $1}' | head -1)
            [ -n "$NEW_HASH" ] && sed -i "s|${CURRENT_HASH}|${NEW_HASH}|g" /etc/opkg/distfeeds.conf
        fi

sed -i 's|\(releases/[0-9]\{1,\}\.[0-9]\{1,\}\)/|\1-SNAPSHOT/|' "/etc/opkg/distfeeds.conf" 2>/dev/null
sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf" 2>/dev/null

test $ver -lt 3 && {
    ver=3
    
    HOSTNAME="samsungTV"
    TAG="googleDNS"
    MAC=""
    IPADDR=""
    DNS1="8.8.4.4"
    DNS2="8.8.8.8"
    
    uci -q batch <<EOF
        set dhcp.${HOSTNAME}="host"
        set dhcp.${HOSTNAME}.name="${HOSTNAME}"
        set dhcp.${HOSTNAME}.mac="${MAC}"
        set dhcp.${HOSTNAME}.ip="${IPADDR}"
        set dhcp.${HOSTNAME}.tag="${TAG}"
        set dhcp.${TAG}="tag"
        set dhcp.${TAG}.dhcp_option="6,${DNS1},${DNS2}"
EOF
    
    uci -q add dhcp domain
    uci -q set "dhcp.@domain[-1].name=time.android.com"
    uci -q set "dhcp.@domain[-1].ip=203.107.6.88"
    uci -q commit dhcp
    
    [ "$debug" = "1" ] && echo "Version updated to: $ver"
}

test $ver -lt 5 && {
    ver=5
    # ttyd
    if [ -e /etc/config/ttyd ]; then
        uci -q delete ttyd.@ttyd[0].interface
    fi
    
    for samba in samba4 samba; do
        if [ -e "/etc/config/$samba" ]; then
            uci -q set "$samba.@samba[0].interface='lan wan'"
            uci -q commit "$samba"
	    sed -i 's/invalid users = root/# invalid users = root/g' /etc/samba/smb.conf.template
        fi
    done
    
    uci -q set dropbear.@dropbear[0].Interface='lan'
    uci -q set dropbear.main.Interface=='lan'
    uci -q commit dropbear

    uci -q batch <<EOF
        set luci.apply.rollback=30
        set luci.apply.holdoff=2
        commit luci
EOF

    if [ -f /etc/config/nginx ]; then
        uci -q batch <<EOF
            set nginx.global.uci_enable='true'
            del nginx._lan
            del nginx._redirect2ssl
            add nginx server
            rename nginx.@server[0]='_lan'
            set nginx._lan.server_name='_lan'
            add_list nginx._lan.listen='80 default_server'
            add_list nginx._lan.listen='[::]:80 default_server'
            add_list nginx._lan.include='conf.d/*.locations'
            set nginx._lan.access_log='off; # logd openwrt'
            commit nginx
EOF
        service nginx restart 2>/dev/null
    fi

    if [[ -f /etc/config/uhttpd ]] ;then
        uci -q batch <<EOF
            set luci.main.sessiontime='86400'
            set luci.main.sessionkeep='1'
            set luci.main.reqtimeout='60'
            set uhttpd.main.rfc1918_filter=0
            set uhttpd.main.session_timeout='86400'
            set uhttpd.main.session_keepalive='1'
            set uhttpd.main.cookie_lifetime='86400'
            set uhttpd.main.instances=4
            set uhttpd.main.max_connections=100
            set uhttpd.main.max_requests=500
            set uhttpd.main.network_timeout=30
            set uhttpd.main.script_timeout='60'
            set uhttpd.main.network_timeout='30'
            set uhttpd.main.http_keepalive='20'
            commit luci
            commit uhttpd
EOF
        /etc/init.d/uhttpd restart 2>/dev/null
        /etc/init.d/system restart 2>/dev/null
        /etc/init.d/network restart 2>/dev/null
        /etc/init.d/dnsmasq restart 2>/dev/null
    fi

    if [ -f /etc/config/snmpd ]; then
        uci -q batch <<EOF
            set snmpd.default_settings=snmpd
            set snmpd.default_settings.agentaddress='udp:127.0.0.1,udp6:[::1]:161'
            set snmpd.default_settings.community='public'
            set snmpd.default_settings.version='v2c'
            commit snmpd
EOF
    fi
    
    [ "$debug" = "1" ] && echo "Version updated to: $ver"
}

for service in miniupnpd turboacc ttyd mwan3 watchdog; do
    [ -f "/etc/init.d/$service" ] && /etc/init.d/$service restart 2>/dev/null
done

[ -f '/usr/libexec/login.sh' ] && sed -i '$ s|exec /bin/login$|exec /bin/sh -l|' /usr/libexec/login.sh 2>/dev/null

uci -q set base_config.@base[0].ver="$ver"
uci -q commit base_config



if check_service "dockerman.lua"; then
    /etc/init.d/dockerd enable 2>/dev/null
    /etc/init.d/dockerd restart 2>/dev/null
else
    /etc/init.d/dockerd disable 2>/dev/null
    /etc/init.d/dockerd stop 2>/dev/null
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf" 2>/dev/null
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-* 2>/dev/null

exit 0
