#!/bin/sh

# SPDX-License-Identifier: MIT
#
# Copyright (C) 2025 by sirpdboy <sirpdboy@qq.com>

generate_mac() {
    od -An -N6 -tx1 /dev/urandom | awk '{
        printf("02:%02x:%02x:%02x:%02x:%02x\n", 
        and($1, 0xFE), $2, $3, $4, $5, $6) }'
}
getmac() {
hexdump -n6 -e '/1 "%02x:"' /dev/urandom | sed 's/:$//'
}
if [ $# -eq 0 ]; then
    echo "Usage: ${0##*/} <INTERFACE>..."
    echo "Example: ${0##*/} eth0 eth1"
    exit 1
fi

for nic in "$@"; do
    if [ "$nic" = "lo" ] || ! ip -o link show dev "$nic" >/dev/null 2>&1; then
        exit 1
    fi
done

for nic in "$@"; do
    new_mac=$(hexdump -n6 -e '/1 "%02x:"' /dev/urandom | sed 's/:$//')
    [ "$new_mac" == "" ] && new_mac=$(rgmac)
    _section=$(uci show network | sed -En "/@device\[.*\]\.name='$nic'/ {s|\.name=.*$|| p}")
    [ "$_section" == "" ] && _section="network.$(uci add network device)" && uci set ${_section}.name="$nic"
    eval "uci set ${_section}.macaddr=$(echo \"\${new_mac}\")"
    echo "Changed $nic MAC to $new_mac"
done
uci commit network
/etc/init.d/network reload
