#!/bin/sh
[ -f '/etc/rpcd_19_cpu.js' ] &&	mv -f '/etc/rpcd_19_cpu.js' '/www/luci-static/resources/view/status/include/19_cpu.js'
[ -f '/etc/rpcd_29_ports.js' ] && mv -f '/etc/rpcd_29_ports.js' '/www/luci-static/resources/view/status/include/29_ports.js'
[ -f '/etc/rpcd_31_user.js' ] && mv -f '/etc/rpcd_31_user.js' '/www/luci-static/resources/view/status/include/31_user.js'
[ -f '/www/luci-static/resources/view/status/include/21_ethinfo.js' ] && rm -rf /www/luci-static/resources/view/status/include/21_ethinfo.js
/etc/init.d/rpcd restart
exit 0
