#!/bin/sh
[ -f /etc/samba4.init ] && mv -f /etc/samba4.init /etc/init.d/samba4

rm -f /tmp/luci-indexcache* 2>/dev/null
rm -f /tmp/luci-modulecache/* 2>/dev/null  # OpenWrt 21.02
rm -f /tmp/luci-indexcache

rm -rf /tmp/luci-*
exit 0